name: AWS automation project 1

on:
  push:
    branches:
      - main

jobs:
  deploy-and-scan:
    name: Deploy WordPress on EC2 and IaC Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v2

        #Terraform setup
      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
        # AWS credetials setup
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-2
       # Innitialize Terraform
      - name: Initialize Terraform
        run: terraform init

       # Deploy Terraform
      - name: Deploy Terraform
        run: terraform apply -auto-approve
